### ISSUE TITLE
Small bug: images not appearing at load time on Safari

### ISSUE THREAD

**Issue by champagnealexandre** [floyd-li/hugo-theme-itheme#14]
Hi!

First thank you so much for this theme, it’s really nice, great work.

I have encountered a very minor bug. On Safari, the images do not appear when loading the page, and they all appear as soon as the viewer scrolls the page.

I have checked with Chrome for macOS and the page appears correctly (the images appear as soon as the page is loaded). Same thing with Edge, the bug is not present. On my iPhone, the page also loads correctly with Safari. So it’s really an issue with Safari on macOS only.

My Safari version is 16.4 (18615.1.26.110.1).
My macOS version is Ventura 13.3.1 (a) (22E772610a).

I’m quite new to Hugo/CSS so I’m not entirely sure how to fix the bug myself, sorry!

**Comment by floyd-li** [comment]
Hi thanks for your feedback. just checked with Safari and i found this issue, also have some style issue. seems it's little incompatible with safari. i may try to fix it in the future.

**Comment by champagnealexandre** [comment]
Here’s my fix:

```
/* fix bug where image on front page doesn’t appear right away on safari */
html.js .tile.large-load .image {
opacity: 1;
}
```

**Comment by floyd-li** [comment]
oh thanks for your contribution, i'll appreciate if you open a pr to fix this issue
