### ISSUE TITLE
date & cover image doesn't show up

### ISSUE THREAD

**Issue by mansoorbarri** [floyd-li/hugo-theme-itheme#5]
#### Date: 
The date shows up as the tag *(i presume)*:
![image](https://user-images.githubusercontent.com/90044118/227759356-3b546bb5-9239-48e2-9471-b26c7aaaf333.png)
this shows everywhere in the place of the actual date. 

#### Cover Image: 
as seen in the screenshot above, the cover image doesn't show up to even though the image can be accessed via the URL in the `href` tag. 

webpage link: [beta.mortgagemarket.uk.com/public/](http://beta.mortgagemarket.uk.com/public/)

**Comment by floyd-li** [comment]
Hi thanks for the feedback, can you provide the front matter of the markdown file? like this
```
---
title: "iTheme for Hugo"
date: 2023-03-25T15:04:53+08:00
description: "an introduce for iTheme"
draft: false
author: "Floyd Li"
cover: "https://images.pexels.com/photos/11035544/pexels-photo-11035544.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
tags: ["Introduce","Demo"]
theme: "light"
---
```

**Comment by floyd-li** [comment]
i checked the site and the `animation.js` file load failed, seems it's a bug of the theme when you use the sub directory like `somsite.com/public`.
i'll fix it next week.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/16473062/227780910-f18b1849-9cb6-4400-a6f3-b475a6e5c159.png">

**Comment by floyd-li** [comment]
> as seen in the screenshot above, the cover image doesn't show up to even though the image can be accessed via the URL in the href tag.

@mansoorbarri this bug has been fixed, please update the theme.

**Comment by mansoorbarri** [comment]
thank you, the cover is fixed now but the date doesn't show up still.
screenshot of the site and front matter:
![image](https://user-images.githubusercontent.com/90044118/227786145-4aab6d86-dd98-4296-ac01-79eb13eb6cb6.png)

```
---
title: "First-Time Buyers in the UK: 6 Things to Be Careful About When Getting a Mortgage"
date: 2023-03-20T13:06:38+08:00
description: "First-time buyers in the UK, don't miss out on these 6 crucial tips for getting a mortgage. Read on to secure the best deal for your needs. #mortgages #firsttimebuyers"
author: "Mansoor Barri"
cover: "https://beta.mortgagemarket.uk.com/public/images/first-time-buyer/main.png"
tags: ["UK", "Mortgages", "FirstTimeBuyers"]
theme: "light"
---
```

**Comment by floyd-li** [comment]
@mansoorbarri hmmm it's little strange... i tested with your `front matter` and it displayed well locally
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/16473062/227861740-9f640b93-ac05-4801-b055-e414beea3406.png">

can you try `hugo version` command to check the version? 
FYI mine is `hugo v0.111.3+extended darwin/amd64 BuildDate=unknown`
will you try update to the latest `hugo` and check the result again? if this issue still exist please give me feedback.

btw, i just fixed some url issues for this theme, you can update the theme again :)
