### ISSUE TITLE
Pictures don't seem to be working

### ISSUE THREAD

**Issue by mansoorbarri** [floyd-li/hugo-theme-itheme#6]
pictures embedded as links don't work apparently, its the same on test side and the built version. The error is on your demo site too: 
![image](https://user-images.githubusercontent.com/90044118/228370905-7b7277b0-2f5c-4356-a6ff-8c86fd22d089.png)

My site: [blog.mortgagemarket.uk.com/authors/](https://blog.mortgagemarket.uk.com/authors/)

code: 
```
---
title: "Meet Our Authors"
date: 2023-03-22
description: "Discover the people behind Mortgage Market UK's insightful articles on our 'Meet Our Authors' page. Get to know our talented writers today!"
theme: "light"
cover: "https://example.com"
---

At Mortgage Market UK, we're committed to bringing you insightful articles from a diverse group of authors. From mortgage experts to industry insiders, our writers cover a range of topics to help you navigate the complex world of mortgages.

![picture should be here](https://github.com/mansoorbarri/website/blob/main/public/images/main.png?raw=true)

#### Mansoor Barri | Head Of IT 
```

**Comment by floyd-li** [comment]
@mansoorbarri  thanks for your feedback. this issue has been fixed, please update the theme
